name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_praveen
        chmod 600 ~/.ssh/id_praveen
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_praveen
      shell: bash

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H 74.225.252.178 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      env:
        REMOTE_SERVER: "finkuser@74.225.252.178"
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_SERVER "cd /home/finkuser/testing/testing/ && git pull origin main"
      shell: bash
