name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Updated to the latest stable version

    - name: Set up SSH
      run: |
        private_kay = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOeH5IWyF2GGm2HvgrPYEl9eg6NfnHtISB8XQ4n1VEc finkuser@core-backend-services
        chmod 600 private_key.pub
        eval $(ssh-agent -s)
        ssh-add private_key
      shell: bash

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 74.225.252.178 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      env:
        REMOTE_SERVER: "finkuser@74.225.252.178"
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_SERVER "cd /home/finkuser/testing/testing/ && git pull origin main"
        rm private_key 
