name: Deploy to VM

on:
  push:
    branches:
      - main  # Ensure this matches your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed2551
        chmod 600 ~/.ssh/id_ed2551  # Secure key permissions
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed2551
      shell: bash

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh  # Ensure directory exists
        ssh-keyscan -H 74.225.252.178 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      env:
        REMOTE_SERVER: "finkuser@74.225.252.178"
      run: |
        ssh -o  StrictHostKeyChecking=ssh $REMOTE_SERVER "cd /home/finkuser/testing && git pull origin main"
      shell: bash
