name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519
      shell: bash

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 74.225.252.178 >> ~/.ssh/known_hosts

    - name: Check SSH Configuration and Remote
      run: |
        echo "SSH Private Key:"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | cut -c 1-20
        echo "Remote Server: ${{ env.REMOTE_SERVER }}"
        ssh -vT ${{ env.REMOTE_SERVER }}
      env:
        REMOTE_SERVER: "finkuser@74.225.252.178"
      shell: bash

    - name: Deploy via SSH
      env:
        REMOTE_SERVER: "finkuser@74.225.252.178"
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_SERVER "cd /home/finkuser/testing && git pull origin main"
      shell: bash

    - name: Start the Docker file
      run: |
        docker build -t testing /home/finkuser/testing
        docker run --rm --name praveen /home/finkuser/testing .
        echo "Successfully started docker..."

